Service:
  Port: :19610
  DebugMode: true
  MaxPageSize: 100
  MinPageSize: 1
  Host: http://localhost:19610
  UploadSavePath: storage/uploads/
  UploadMaxImgSize: 5
  UploadVideoMaxSize: 50
  UploadVideoAllowExts:
    - mp4
  UploadImageAllowExts:
    - jpeg
    - jpg
    - png

Logger:
  DebugFile: log/debug/debug.log
  AccessFile: log/access/access.log
  MaxSize: 5
  MaxAge: 30

DB:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 127.0.0.1
  Port: 3306
  DBName: shop
  TablePrefix: shop_
  Charset: utf8mb4
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Host: 127.0.0.1:6379
  Password:
  DefaultDB: 0
